server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trainer-training-summary
      auto-index-creation: true
#      username: admin
#      password: admin

  application:
    name: TRAINER-WORKLOAD-SERVICE

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false   # false = use external broker
    jms:
      pub-sub-domain: false  # false = Point-to-Point (queue), true = Topic


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%6.32X{transactionId}] %msg%n"