server:
  port: 8082

spring:
  application:
    name: TRAINER-WORKLOAD-SERVICE
  datasource:
    url: jdbc:h2:mem:trainerworkloaddb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false   # false = use external broker
    jms:
      pub-sub-domain: false  # false = Point-to-Point (queue), true = Topic


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%6.32X{transactionId}] %msg%n"